name: test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@main
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Install dependencies
      run: make common-deps
    - name: Run tests
      run: make test-coverage
    - name: Archive test and code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
            test/*.xml
            **/cover.out
    - name: Produce Summary Report
      if: always()    # run this step even if previous step failed
      uses: phoenix-actions/test-reporting@v15
      with:
        name: report
        path: test/*.xml
        reporter: java-junit
        output-to: 'step-summary'
